input.onButtonPressed(Button.B, function () {
    Blinker.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
    Blinker.showColor(neopixel.colors(NeoPixelColors.Black))
})
let Blinker: neopixel.Strip = null
let Scheinwerfer = neopixel.create(DigitalPin.P0, 1, NeoPixelMode.RGB)
Blinker = neopixel.create(DigitalPin.P8, 1, NeoPixelMode.RGB)
basic.forever(function () {
    Scheinwerfer.showColor(neopixel.colors(NeoPixelColors.Blue))
    pins.servoWritePin(AnalogPin.P1, Math.map(pins.analogReadPin(AnalogPin.P2), 0, 1023, 0, 180))
})
